#!/bin/sh

take () {

printf "img_$(date +%F%T)".png > ~/.config/scripts/magick-screenshot/img.txt
magick import ~/.config/scripts/magick-screenshot/"$(cat ~/.config/scripts/magick-screenshot/img.txt)"
notify-send screenshot_initiated "$(cat ~/.config/scripts/magick-screenshot/img.txt)" -i ~/.config/scripts/magick-screenshot/"$(cat ~/.config/scripts/magick-screenshot/img.txt)"
rm -rf ~/.config/scripts/magick-screenshot/img.txt && killall -9 magick-import
}

while true
do

take

done